// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 32
(function(w,g){w[g]=w[g]||{};w[g].e=function(s){return eval(s);};})(window,'google_tag_manager');(function(){
var k=this,ca=null;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var da=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,ea=function(a){if(null==a)return String(a);var b=da.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},fa=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},ga=function(a){if(!a||"object"!=ea(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!fa(a,"constructor")&&!fa(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}for(var c in a);return void 0===
c||fa(a,c)};var ha=function(){},r=function(a){return"function"==typeof a},v=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},ia=function(a){return"number"==ea(a)&&!isNaN(a)},ja=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},ka=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},z=function(a){return Math.round(Number(a))||0},la=function(a){var b=[];if(v(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));
return b},B=function(){this.prefix="gtm.";this.B={}};B.prototype.set=function(a,b){this.B[this.prefix+a]=b};B.prototype.get=function(a){return this.B[this.prefix+a]};B.prototype.contains=function(a){return void 0!==this.get(a)};
var ma=function(a,b,c){try{return a["14"](a,b||ha,c||ha)}catch(d){}return!1},na=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=ka(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},oa=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},pa=function(a){for(var b=0;b<a.length;b++)a[b]()},qa=(new Date).getTime(),ra=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c};var F=window,G=document,sa=navigator,H=function(a,b){var c=F[a],d="var "+a+";";if(k.execScript)k.execScript(d,"JavaScript");else if(k.eval)if(null==ca&&(k.eval("var _et_ = 1;"),"undefined"!=typeof k._et_?(delete k._et_,ca=!0):ca=!1),ca)k.eval(d);else{var e=k.document,f=e.createElement("script");f.type="text/javascript";f.defer=!1;f.appendChild(e.createTextNode(d));e.body.appendChild(f);e.body.removeChild(f)}else throw Error("goog.globalEval not available");F[a]=void 0===c?b:c;return F[a]},I=function(a,
b,c){return("http:"==F.location.protocol?b:a)+c},ta=function(a){var b=G.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},ua=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},J=function(a,b,c){var d=G.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;ua(d,b);c&&(d.onerror=c);ta(d)},va=function(a,b){var c=G.createElement("iframe");c.height="0";c.width="0";c.style.display=
"none";c.style.visibility="hidden";ta(c);ua(c,b);void 0!==a&&(c.src=a);return c},L=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},M=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},N=function(a){F.setTimeout(a,0)},wa=!1,xa=[],ya=function(a){if(!(a&&"readystatechange"==a.type&&"interactive"!=G.readyState&&"complete"!=G.readyState||wa)){wa=!0;for(var b=0;b<xa.length;b++)xa[b]()}},
za=0,Aa=function(){if(!wa&&140>za){za++;try{G.documentElement.doScroll("left"),ya()}catch(a){F.setTimeout(Aa,50)}}},Ba=function(a,b){return a&&b&&a.attributes[b]?a.attributes[b].value:null},Ca=!1,Da=[],Ea=function(){if(!Ca){Ca=!0;for(var a=0;a<Da.length;a++)Da[a]()}};var Fa=new B,Ga=new B,Ha=ha,O=[],Ja=!1,Ka=!1,La="//www.googletagmanager.com/a?e=aocc&cb="+Math.round(2147483647*Math.random()),Ma=function(a){var b=!1;return function(){!b&&r(a)&&N(a);b=!0}},Oa=function(){for(var a=!1;!Ja&&0<O.length;){Ja=!0;var b;var c=O.shift(),d=void 0;for(d in c)if(c.hasOwnProperty(d)){var e=d,f=c[d];Fa.set(e,f);for(var g=Na,h=f,p={},m=p,l=e.split("."),q=0;q<l.length-1;q++)m=m[l[q]]={};m[l[l.length-1]]=h;g(p,Ga.B)}var n=c.event;if(n){var t=Ma(c.eventCallback),w=c.eventTimeout;
w&&F.setTimeout(t,Number(w));b=Ha(n,t)}else b=!1;a=b||a;Ja=!1}return!a},P=function(a,b){if(2==b){for(var c=Ga.B,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Fa.get(a)},Na=function(a,b){for(var c in a)if(fa(a,c)){var d=a[c];v(d)?(v(b[c])||(b[c]=[]),Na(d,b[c])):ga(d)?(!Ka&&v(b[c])&&(L(La),Ka=!0),ga(b[c])||(b[c]={}),Na(d,b[c])):b[c]=d}};var Pa={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Qa={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],
nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Ra=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Sa=function(){var a=P("gtm.whitelist"),b=a&&Ra(la(a),Pa),c=P("gtm.blacklist")||P("tagTypeBlacklist"),d=c&&Ra(la(c),Qa),e={};return function(f){var g=f&&f["14"];if(!g)return!0;if(void 0!==e[g.b])return e[g.b];var h=!0;if(a)e:{if(0>ja(b,g.b))if(g.c&&0<g.c.length)for(var p=0;p<g.c.length;p++){if(0>
ja(b,g.c[p])){h=!1;break e}}else{h=!1;break e}h=!0}var m=!1;if(c){var l;if(!(l=0<=ja(d,g.b)))e:{for(var q=g.c||[],n=new B,t=0;t<d.length;t++)n.set(d[t],!0);for(t=0;t<q.length;t++)if(n.get(q[t])){l=!0;break e}l=!1}m=l}return e[g.b]=!h||m}};var Ta=null;var _e=function(){return Ta};_e.b="e";_e.c=["google"];var _v=function(a){var b=P(a["19"].replace(/\\\./g,"."),a[""]);return void 0!==b?b:a[""]};_v.b="v";_v.c=["google"];var _f=function(){return String(P("gtm.referrer")||G.referrer)};_f.b="f";_f.c=["google"];
var Ua=G.createElement("a"),Va=function(a){var b=F.location,c=b.hash?b.href.replace(b.hash,""):b.href,d=P("gtm.url");d&&(Ua.href=c=String(d),b=Ua);var e=(b.protocol.replace(":","")||F.location.protocol.replace(":","")).toLowerCase();switch(a["6"]){case "protocol":c=e;break;case "host":c=(b.hostname||F.location.hostname).split(":")[0].toLowerCase();break;case "port":c=String(1*(b.hostname?b.port:F.location.port)||("http"==e?80:"https"==e?443:""));break;case "path":c="/"==b.pathname.substr(0,1)?b.pathname:"/"+b.pathname;
break;case "query":c=b.search.replace("?","");break;case "fragment":c=b.hash.replace("#","")}
return c},_u=Va;_u.b="u";_u.c=["google"];var _cn=function(a){return 0<=String(a["1"]).indexOf(String(a["2"]))};_cn.b="cn";_cn.c=["google"];var _eq=function(a){return String(a["1"])==String(a["2"])};_eq.b="eq";_eq.c=["google"];var _re=function(a){return RegExp(a["2"],a[""]?"i":void 0).test(a["1"])};_re.b="re";_re.c=["google"];var $a=function(a,b){return a<b?-1:a>b?1:0};var Q,ab,bb,cb,db=function(){return k.navigator?k.navigator.userAgent:null};cb=bb=ab=Q=!1;var eb;if(eb=db()){var fb=k.navigator;Q=0==eb.lastIndexOf("Opera",0);ab=!Q&&(-1!=eb.indexOf("MSIE")||-1!=eb.indexOf("Trident"));bb=!Q&&-1!=eb.indexOf("WebKit");cb=!Q&&!bb&&!ab&&"Gecko"==fb.product}var R=ab,gb=cb,hb=bb,kb=function(){var a=k.document;return a?a.documentMode:void 0},lb;
e:{var mb="",nb;if(Q&&k.opera)var ob=k.opera.version,mb="function"==typeof ob?ob():ob;else if(gb?nb=/rv\:([^\);]+)(\)|;)/:R?nb=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:hb&&(nb=/WebKit\/(\S+)/),nb)var pb=nb.exec(db()),mb=pb?pb[1]:"";if(R){var qb=kb();if(qb>parseFloat(mb)){lb=String(qb);break e}}lb=mb}
var rb=lb,sb={},T=function(a){var b;if(!(b=sb[a])){for(var c=0,d=String(rb).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",p=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var q=m.exec(h)||["","",""],n=l.exec(p)||["","",""];if(0==q[0].length&&0==n[0].length)break;c=$a(0==q[1].length?0:parseInt(q[1],10),0==n[1].length?0:parseInt(n[1],10))||$a(0==q[2].length,
0==n[2].length)||$a(q[2],n[2])}while(0==c)}b=sb[a]=0<=c}return b},tb=k.document,ub=tb&&R?kb()||("CSS1Compat"==tb.compatMode?parseInt(rb,10):5):void 0;if(gb||R){var vb;if(vb=R)vb=R&&9<=ub;vb||gb&&T("1.9.1")}R&&T("9");var Ab=function(a,b){var c="";R&&!wb(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(xb)a.srcdoc=d;else if(yb){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else zb(a,d)},xb=hb&&"srcdoc"in document.createElement("iframe"),yb=gb||hb,zb=function(a,b){R&&T(7)&&!T(10)&&Bb(b)&&(b=Cb(b));var c=function(){a.contentWindow.goog_content=
b;a.src="javascript:window.goog_content"};R&&!wb(a)?Db(a,c):c()},wb=function(a){try{return Boolean(a.contentWindow.document)}catch(b){return!1}},Eb=0,Db=function(a,b){var c="goog_rendering_callback"+Eb++;window[c]=b;R&&T(6)&&!T(7)?a.src="javascript:'<script>window.onload = function() { document.write(\\'<script>(function() {document.domain = \""+document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation()})()<\\\\/script>\\');document.close();};\x3c/script>'":
a.src="javascript:'<script>(function() {document.domain = \""+document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Bb=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Cb=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2013 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var Mb=function(a,b,c,d){return function(e){e=e||F.event;var f=e.target||e.srcElement||{},g=!1;if("LINK_CLICK"==a){for(var h=f,p=0;h&&"a"!=String(h.tagName).toLowerCase()&&100>p;p++)h=h.parentElement;h&&"a"!=String(h.tagName).toLowerCase()&&(h=null);f=h;g=!f||!f.href||e.ctrlKey||e.shiftKey||null==e.which&&4==e.button||2===e.which||3===e.which||e.altKey||!0===e.metaKey}if(e.defaultPrevented||!1===e.returnValue||e.Oa&&e.Oa()){if(!c&&f){var m={simulateDefault:!1};U(a,f,m,d)}}else{var l=/(iPad|iPhone|iPod)/g.test(sa.userAgent);
if(f){var m={},q=U(a,f,m,d);m.simulateDefault=!q&&b&&!g;if(m.simulateDefault){var n=Lb(f).toLowerCase();switch(n){case "_blank":l?(m.simulateDefault=!1,g=!0):(m.targetWindowName="gtm_autoEvent_"+(new Date).getTime(),m.targetWindow=F.open("",m.targetWindowName));break;case "":m.targetWindow=F.frames.self;break;case "_self":case "_parent":case "_top":m.targetWindow=F.frames[n.substring(1)];break;default:l&&!F.frames[n]?(m.simulateDefault=!1,g=!0):(F.frames[n]||(m.targetWindowName=n),m.targetWindow=
F.frames[n]||F.open("",n))}!g&&e.preventDefault&&e.preventDefault()}e.returnValue=q||!b||g;return e.returnValue}return!0}}},U=function(a,b,c,d){var e=d||2E3,f={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||Ba(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":f.event="gtm.linkClick";f["gtm.elementUrl"]=b.href;f.eventTimeout=e;f.eventCallback=Nb(b,c);break;case "FORM_SUBMIT":f.event="gtm.formSubmit";f["gtm.elementUrl"]=b.action;c.jsFormSubmit?
c.waitForTags&&(f.eventTimeout=e,f.eventCallback=function(){G.gtmSubmitFormNow=!0;b.submit()}):(f.eventTimeout=e,f.eventCallback=Ob(b,c));break;case "CLICK":f.event="gtm.click";f["gtm.elementUrl"]=b.formAction||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return F["dataLayer"].push(f)},Lb=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "form":b="_self"}return b},Nb=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?
b.targetWindow.location.href=a.href:(c=c||(new Date).getTime(),500>(new Date).getTime()-c&&F.setTimeout(Nb(a,b,c),25)))}},Ob=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&(d=a.target,a.target=b.targetWindowName);G.gtmSubmitFormNow=!0;a.submit();b.targetWindowName&&(a.target=d)}else c=c||(new Date).getTime(),500>(new Date).getTime()-c&&F.setTimeout(Ob(a,b,c),25)}},Pb=function(a,b,c,d){var e,f;switch(a){case "CLICK":if(G.gtmHasClickListenerTag)return;
G.gtmHasClickListenerTag=!0;e="click";f=function(a){U("CLICK",a.target||a.srcElement||{},{},d);return!0};break;case "LINK_CLICK":if(G.gtmHasLinkClickListenerTag)return;G.gtmHasLinkClickListenerTag=!0;e="click";f=Mb(a,b||!1,c||!1,d);break;case "FORM_SUBMIT":if(G.gtmHasFormSubmitListenerTag)return;G.gtmHasFormSubmitListenerTag=!0;e="submit";f=Mb(a,b||!1,c||!1,d);break;default:return}M(G,e,f,!1)};var Sb,Tb;
var cc=function(a){return function(){}},dc=function(a){return function(){}};
var fc=!1,jc=!1,_ga=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];q.push(b)}function e(b,c){void 0!==a[c]&&d(b,a[c])}function f(b,c){void 0!==a[c]&&d(b,Number(a[c]))}function g(a,b){if(b)for(var c=0;c<b.length;c++){var e=[a];v(b[c])?e.push.apply(e,b[c]):e.push(b[c]);"_setCustomVar"==e[0]&&void 0===e[3]||d.apply(this,e)}}function h(b,c){void 0!==a[c]&&d("_set",b,a[c])}function p(b,c){void 0!==a[c]&&(t+="&"+b+"="+a[c])}function m(a,b){t+="&"+a+"="+b}function l(a,b){return a.charAt(0)==
b?a.substring(1):a}var q=H("_gaq",[]),n="";void 0==a[""]?n="gtm"+qa++ +".":""!==a[""]&&(n=a[""]+".");e("_setAccount","0");
var t="";
if(""!==t){var w=new B,C=l(F.location.search,"?"),D=l(F.location.hash,"#");C&&na(w,C);D&&a[""]&&na(w,D);w.contains("gclid")&&m("gclid",oa(w.get("gclid")));w.contains("gclsrc")&&m("gclsrc",oa(w.get("gclsrc")));w.contains("dclid")&&m("dclid",oa(w.get("dclid")));d("_set","campaignParams",t)}
a["18"]&&d("_require","inpage_linkid","//www.google-analytics.com/plugins/ga/inpage_linkid.js");

e("_setCampaignTrack","3");
e("_setClientInfo","5");e("_setDetectFlash","9");e("_setDetectTitle","10");d("_set","hitCallback",function(){if(r(a[""]))a[""]();b()});if(a["22"]){var K=void 0==a[""]?
a[""]:z(a[""]);d("_trackEvent",a["12"],a["11"],a["13"],K,a[""]);}else if(a[""]){}else if(a[""]){}else if(a[""]){}else if(a[""]){}else if(a[""]){}else if(a[""]){}else if(a[""]){}else d("_trackPageview");
var W=function(){F._gat||c()};if(a[""])jc||(jc=!0,J(I("https://","http://","stats.g.doubleclick.net/dc.js"),W,c));else if(!fc){var ba=a["8"]?".google-analytics.com/u/ga_debug.js":".google-analytics.com/ga.js";fc=!0;J(I("https://ssl","http://www",ba),W,c)}};_ga.b="ga";_ga.c=["google"];
var kc=function(a,b){var c=ra(a,"23",!0),d=ra(a,"4",!0),e=z(a["24"]);0>=e&&(e=2E3);Pb("LINK_CLICK",!!c,!!d,e);if(!G.addEventListener){var f=function(a){a=a||F.event;for(var b=a.target||a.srcElement||{};b;)b.onclick&&!b.onclick.gtmOnclickWrapper&&(b.onclick=kc.Pa(b.onclick)),b=b.parentElement};M(G,"mousedown",f,!1);M(G,"keydown",function(a){a=a||F.event;13==a.keyCode&&f(a)},!1)}N(b)};kc.Pa=function(a){var b=function(b){b=b||F.event;
var d=a.call(this,b);b.returnValue=!1!==d&&(b.returnValue||void 0===b.returnValue);return d};b.gtmOnclickWrapper=!0;return b};var _lcl=kc;_lcl.b="lcl";var _sp=function(a,b,c){J("//www.googleadservices.com/pagead/conversion_async.js",function(){var d=F.google_trackConversion;r(d)?(d({google_conversion_id:a["15"],google_conversion_label:a["17"],google_custom_params:a["7"]||{},google_remarketing_only:!0}),b()):c()},c)};_sp.b="sp";_sp.c=["google"];var Hc=function(){this.g=[]};Hc.prototype.set=function(a,b){this.g.push([a,b]);return this};Hc.prototype.A=function(a,b){for(var c={},d=0;d<this.g.length;d++){var e=Y(this.g[d][0],a,b),f=Y(this.g[d][1],a,b);c[e]=f}return c};var Ic=function(a){this.index=a};Ic.prototype.A=function(a,b){var c=Jc[this.index];if(c&&!b(c)){var d=c["16"];if(a){if(a.get(d))return;a.set(d,!0)}c=Y(c,a,b);a&&a.set(d,!1);return ma(c)}};
for(var _M=function(a){return new Ic(a)},Lc=function(a){this.A=function(b,c){for(var d=[],e=0;e<a.length;e++)d.push(Y(Kc[a[e]],b,c));return d.join("")}},_T=function(a){return new Lc(arguments)},Mc=function(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return!0;return!1}this.A=function(c,d){if(a[0]instanceof Ic&&b(8)&&b(16))return'google_tag_manager["GTM-NCXRS4"].macro('+
a[0].index+")";for(var e=String(Y(a[0],c,d)),f=1;f<a.length;f++)e=X[a[f]](e);return e}},_E=function(a,b){return new Mc(arguments)},Y=function(a,b,c){var d=a;if(a instanceof Ic||a instanceof Hc||a instanceof Lc||a instanceof Mc)return a.A(b,c);if(v(a))for(var d=[],e=0;e<a.length;e++)d[e]=Y(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=Y(a[f],b,c))}return d},Nc=function(a,b){var c=b[a],d=c;if(c instanceof Ic||c instanceof Mc||c instanceof Lc)d=c;else if(v(c))for(var d=
[],e=0;e<c.length;e++)d[e]=Nc(c[e],b);else if("object"==typeof c){var d=new Hc,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],Nc(c[f],b))}return d},Qc=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=Kc[e[1]]);if(1==a)for(var f=Oc(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Pc[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=Oc(e[g])}return c},Oc=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Rc;c+=6,d++){var e=a&&a.charCodeAt(d)||
65;if(65!=e){var f=0,f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Rc=72,Sc=[_cn,_u,'url',_M(0),'thanks.php',_eq,_e,'_event',_M(1),'gtm.js',_sp,'googleCVタグ','976122709','google_conversion_value','google_conversion_color','google_conversion_format','google_conversion_language','google_remarketing_only','0','ffffff','2','en','false',{13:18,14:19,15:20,16:21,17:22},'toowCPPFjgkQ1ea50QM',7,'event',_M(2),'gtm.linkClick',_v,'element url','gtm.elementUrl',_M(3),'q/scout','https://codeiq.jp/index.php','top_banner_big',_ga,'UA-30868502-1',true,'Internal','Link',false,5,'url path','path',_M(4),'/my_feedback','Challenge_over',_re,'.*',_lcl,'リンククリックリスナー','2000',4,'feedback_banner',3,'GoogleAnalytics',1,'googleリマーケティングタグ（S連携）','google_custom_params','true','window.google_tag_params',{17:60,59:61},8,'element classes','gtm.elementClasses','element','gtm.element',_f,'referrer','url hostname','host','element id','gtm.elementId','element target','gtm.elementTarget'],Tc=[],Uc=0;Uc<Sc.length;Uc++)Tc[Uc]=Nc(Uc,Sc);var Kc=Tc,Pc=Qc(0,"14:0,14:1,16:2,1:3,2:4,14:5,14:6,16:7,1:8,2:9,14:10,16:11,15:12,7:23,17:24,21:25,16:26,1:27,2:28,14:29,16:30,19:31,1:32,2:33,2:34,14:36,16:35,0:37,22:38,11:39,12:40,13:35,18:41,3:38,5:38,9:38,10:38,20:38,8:41,21:42,16:43,6:44,1:45,2:46,14:48,2:49,14:50,16:51,23:38,4:38,24:52,21:53,16:47,13:54,21:55,16:56,21:57,16:58,7:62,21:63,16:64,19:65,16:66,19:67,14:68,16:69,16:70,6:71,16:72,19:73,16:74,19:75"),Jc=Qc(1,"G,AD,ABQ,AAAO,CAAAAAw,AAACAAAAAAD,AAACAAAAAAM,AAAAAAAAAAw,CAAAAAAAAAAD,AAACAAAAAAAM,AAACAAAAAAAw"),Vc=Qc(1,"Z,gM,gAgB,BAAw,oAAAB,BAAAAAAD,IAAAAAAM"),Z=Qc(1,"AwP,AAAA-_P,AAAAAAAwP,AAAA69HAwB,AAAAK8HAAG,AQBAAAAAA4"),Wc=Qc(2,"D:B::,c:G::,s:M::,CB:0::");var dd=function(){var a=this;this.r=!1;this.t=[];this.L=[];this.Fa=function(){a.r||pa(a.t);a.r=!0};this.Ea=function(){a.r||pa(a.L);a.r=!0};this.execute=ha},ed=function(){this.i=[];this.Y={};this.M=[];this.o=0};ed.prototype.addListener=function(a){this.M.push(a)};var fd=function(a,b,c,d){if(!c.r){a.i[b]=c;void 0!==d&&(a.Y[b]=d);a.o++;var e=function(){0<a.o&&a.o--;0<a.o||pa(a.M)};c.t.push(e);c.L.push(e)}};var gd=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Vc[b]&&Y(Vc[b],new B,c);a[b]=[d&&ma(d),d]}return a[b]}},hd=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.j(c[d],a.d)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.j(e[d],a.d)[0])return!1;return!0},id=function(a,b){return function(){ma(a,b.Fa,b.Ea)}},jd=Ha=function(a,b){Ta=a;P("tagTypeBlacklist");for(var c={name:a,Ba:b||ha,v:Oc(),w:Oc(),j:gd(),d:Sa()},d=0;d<Wc.length;d++)if(hd(c,Wc[d])){for(var e=c,f=Wc[d],g=f[1],
h=0;h<g.length;h++)e.v[g[h]]=!0;for(var p=f[3],h=0;h<p.length;h++)e.w[p[h]]=!0}var m=[];for(var l=0;l<Rc;l++)if(c.v[l]&&!c.w[l])if(c.d(Z[l])){}else{m[l]=Y(Z[l],new B,c.d);}c.O=m;for(var q=new ed,n=0;n<Rc;n++)if(c.v[n]&&
!c.w[n]&&!c.d(Z[n])){var t=c.O[n],w=new dd;w.t.push(cc(t));w.L.push(dc(t));w.execute=id(t,w);fd(q,n,w,t[""])}q.addListener(c.Ba);for(var C=[],D=0;D<q.i.length;D++){var K=q.i[D];if(K){var x=q.Y[D];void 0!==x?x!=D&&q.i[x]&&q.i[x].t.push(K.execute):C.push(D)}}for(D=0;D<C.length;D++)q.i[C[D]].execute();0<q.o||pa(q.M);Ta=null;return 0<c.O.length};var $={set:function(a,b){var c={};c[a]=b;F["dataLayer"].push(c)},event:function(a){jd(a)},macro:function(a){var b;if(b=Jc[a]){var c=_M(a),d=Sa();b=Y(c,new B,d)}return b},S:{push:function(a){for(var b=arguments,c=0;c<b.length;c++)try{if(r(b[c][0]))b[c][0]();else $[b[c][0]].apply($,[].slice.call(b[c],1))}catch(d){}}},Ma:function(){var a=F["gtm"];if(a){var b=a.a;v(b)&&$.S.push.apply($.S,b);a.a=$.S;xa.push(function(){$.event("gtm.dom")});Da.push(function(){$.event("gtm.load")})}},Na:function(){var a=
F.google_tag_manager;a||(a=F.google_tag_manager={});a["GTM-NCXRS4"]||(a["GTM-NCXRS4"]=$)}};$.Na();$.Ma();(function(){var a=H("dataLayer",[]),b=F.google_tag_manager;xa.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Da.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(O.push.apply(O,b);300<this.length;)this.shift();return Oa()};O.push.apply(O,a.slice(0));N(Oa)})();
if("interactive"==G.readyState||"complete"==G.readyState)ya();else{M(G,"DOMContentLoaded",ya);M(G,"readystatechange",ya);if(G.createEventObject&&G.documentElement.doScroll){var kd=!0;try{kd=!F.frameElement}catch(ld){}kd&&Aa()}M(F,"load",ya)}"complete"===G.readyState?Ea():M(F,"load",Ea);var _vs="res_ts:1389259614120000,srv_cl:59043962,ds:live,cv:32";
})()
